{
 "title": "Java Micrometer",
 "description": "Java metrics exposed with Micrometer",
 "tags": [
  "java",
  "micrometer"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(cpu, kubernetes_namespace)"
   },
   {
    "name": "pod_name",
    "label": "Pod Name",
    "query": "label_values(cpu{kubernetes_namespace =\"$namespace\"}, kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "JVM Memory Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffer Count",
     "type": "graph",
     "description": "An estimate of the number of buffers in the pool",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Buffer Mem Used",
     "type": "graph",
     "description": "An estimate of the memory that the Java virtual machine is using for this buffer pool",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Buffer Capacity",
     "type": "graph",
     "description": "An estimate of the total capacity of the buffers in this pool",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_total_capacity_bytes{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Max Memory",
     "type": "graph",
     "description": "The maximum amount of memory in bytes that can be used for memory management",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_max_bytes{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{id}} ({{area}})"
      }
     ]
    },
    {
     "title": "Used Memory",
     "type": "graph",
     "description": "The amount of used memory",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{id}} ({{area}})"
      }
     ]
    },
    {
     "title": "Committed Memory",
     "type": "graph",
     "description": "The amount of memory in bytes that is committed for  the Java virtual machine to use",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_committed_bytes{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{id}} ({{area}})"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Garbage Collection Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max Data Size",
     "type": "graph",
     "description": "Max size of old generation memory pool",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_max_data_size_bytes{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Live Data Size",
     "type": "graph",
     "description": "Size of old generation memory pool after a full GC",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_live_data_size_bytes{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Promotion Rate",
     "type": "graph",
     "description": "Count of positive increases in the size of the old generation memory pool before GC to after GC",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_promotion_rate_total{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Allocation Rate",
     "type": "graph",
     "description": "Incremented for an increase in the size of the young generation memory pool after one GC to before the next",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_allocation_rate_total{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Pause Count",
     "type": "graph",
     "description": "Time spent in GC pause",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_duration_seconds_count{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{cause}} ({{action}})"
      }
     ]
    },
    {
     "title": "Pause Duration",
     "type": "graph",
     "description": "Time spent in GC pause",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_duration_seconds_sum{kubernetes_pod_name=~\"$pod_name\"}",
       "legendFormat": "{{cause}} ({{action}})"
      }
     ]
    }
   ]
  }
 ]
}